version: "3"
services:
  db:
    image: "postgres"
    restart: "always"
    container_name: "ht_postgres"
    environment:
      POSTGRES_PASSWORD: "super secret password"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
